### ISSUE TITLE
No Makefile

### ISSUE THREAD

**Issue by Namelessys** [max1220/lua-getch#3]
The Makefile is removed with the commit [78d74b0](https://github.com/max1220/lua-getch/commit/78d74b0a62dd94898e3cb8cb7945390a4a5eed28).
So building using make is not possible anymore per default.

https://github.com/max1220/lua-getch/commit/78d74b0a62dd94898e3cb8cb7945390a4a5eed28

**Comment by max1220** [comment]
That is correct. I can re-add a makefile if you can describe why you want a makefile instead of using LuaRocks.
IMHO LuaRock's native build system has several advantages over using a makefile or using LuaRocks makefile support, especially for such a simple library.

One problem that LuaRocks helps solves is dependencies and versioning. See #4 

Also the makefile is significantly more verbose: ~70 lines of makefile vs. ~30 lines of rockspec(including 10 lines of description, the existing makefile does less, is probably less compatible, and requires another language).

If all you want to do is build a simple shared object "single-shot", keep in mind that you can always simply:
```
gcc -O2 -fPIC -I/usr/include/lua5.1 -c src/lua-getch.c -o src/lua-getch.o -DLUAROCK_PACKAGE_VERSION="scm-1" -DLUAROCK_PACKAGE_NAME="lua-getch"
gcc -shared -o getch.so -L/usr/local/lib src/lua-getch.o
```

**Comment by Namelessys** [comment]
There where some problems with the luarocks installation, but i dont remember what it was. Maybe i was trying to use `luarocks install lua-getch` or something like that.
But now it seems to work.

The method of building using `make` was still mentioned in the readme at that time, so i thought it might was a mistake.
Got it running by using the makefile in https://github.com/max1220/lua-getch/commit/78d74b0a62dd94898e3cb8cb7945390a4a5eed28 at the end.

Anway, thx for the answer!

**Comment by max1220** [comment]
@MisterNoNameLP Hey, just for your convenience I've re-added a simple makefile for compiling again(no installation! The previous installation script could malfunction in bad ways, e.g. installing files from different versions into the same directory. Installation across distributions and versions inside a makefile is non-trivial... :P).

The old makefile doesn't have a way of "uninstalling" the module automatically, so **if** you've **installed** using the makefile you probably should uninstall manually(see below), and re-install using luarocks(make sure you don't have any "zombie" installations).

To uninstall manually, simply make sure these files/directories don't exist:
`/usr/local/lib/lua/5.1/getch.so`
`/usr/local/share/lua/5.1/lua-getch`

LuaRocks handles the installation/uninstallation automatically, so no need to worry if you didn't **install**(just compiled and installed manually) using the makefile. Just make sure to be consistent with the `--local` flag to luarocks(install to user instead of system).

(I'm sorry for your inconvenience with the horrible old makefile :P)
